build_all: articulation_points mst_directed strongly_connected

articulation_points:
	g++ -std=c++17 -O3 articulation_points.cpp -o built/articulation_points

mst_directed:
	g++ -std=c++17 -O3 mst_directed.cpp -o built/mst_directed

strongly_connected:
	g++ -std=c++17 -O3 strongly_connected.cpp -o built/strongly_connected

